### ISSUE TITLE
Loading snippet issue

### ISSUE THREAD

**Issue by erekchernicky** [mparticle-integrations/mparticle-javascript-integration-appboy#10]
Hi!

A mutual customer reached out with an issue regarding the Braze<>mParticle SDK. 

This is the error they receive when loading the SDK:

![screen shot 2018-08-07 at 09 09 48](https://user-images.githubusercontent.com/29210744/43797740-672af50c-9a56-11e8-911d-967ee70d4a0c.png)

One of our mobile devs determined this is related to an issue we saw previously with a loading snippet being used in a modular environment. We have a thread on it here:

https://github.com/segment-integrations/analytics.js-integration-appboy/issues/33

In this particular instance, it seems google tag manager is breaking mParticle's use of the loading snippet. 

This issue was created so we can start brainstorming solutions. Our mobile engineer had mentioned trying to formulate a version of the loading snippet that is more resilient. Otherwise, mParticle can load in some way that doesn't use the loading snippet. Either way mParticle will have to update the integration.

Thoughts?

**Comment by samdozor** [comment]
hey @erekchernicky thanks for the issue! I could use a little more clarification on the issue. So far as I know our snippet is exactly what Braze has in their docs, whereas the linked issue seemed related to a non-standard snippet?

Taking mParticle out of the equation - do customers experience this issue using Braze in GTM? I'm curious what's specific to our implementation vs any other customer's that would cause this. I suggest we pick this up in our slack channel together to quickly iterate.

**Comment by froodian** [comment]
> So far as I know our snippet is exactly what Braze has in their docs, whereas the linked issue seemed related to a non-standard snippet?

I agree that this is the case. I think the larger issue in this case (which is what makes it somewhat similar) is that the default integration snippet in the docs which includes the appboyQueue was really built to be included in the `<head>` of an html page where the global scope and the window variable are the same thing. It's possible that it could be updated to be more defensive to scenarios in which the global scope and window variable differ, but for an environment where you're already in JavaScript, I think a cleaner and less error-prone approach to loading the SDK is to include it more directly - e.g. required through npm, or as a file that gets compiled into the total javascript output.

Loading it asynchronously through javascript from the Braze CDN is also still an option if you don't want to have a local module like that though, but if you go down that path, for the sake of stability across these environments where the global scope differs, I would recommend using a simple load function with a done handler and eschewing use of the shimmed methods and the appboyQueue.

In regards to "do customers experience this issue using Braze in GTM" - we haven't received reports of issues like this from customers who use Braze in GTM directly.

**Comment by erekchernicky** [comment]
Hi @samdozor. Froodian summed up the issue best. Any thoughts?

**Comment by samdozor** [comment]
@froodian thanks for the summary. Unfortunately it's a requirement for our customers to be able to load it dynamically (or not load it in some cases based on user consent state or other factors). Would you be able to recommend a loading snippet that would work in all cases? I have to imagine that GTM users have the same issue unless GTM is doing something really tricky.

**Comment by rmi22186** [comment]
@erekchernicky - ^^ I compiled appboy inside of our integration per @froodian's recommendation rather than loading it dynamically.

**Comment by erekchernicky** [comment]
Very nice! TY!

**Comment by rmi22186** [comment]
This was released yesterday. Was delayed a bit due to some internal discussions. Let us know if there are still any issues.
