### ISSUE TITLE
npm version

### ISSUE THREAD

**Issue by dotomaz** [mparticle-integrations/mparticle-javascript-integration-appboy#29]
A new version `2.0.5` was commited in the repo. But the npm version was not updated https://www.npmjs.com/package/@mparticle/web-appboy-kit. 

Is there a reason for that? And when do you plan to release it?

**Comment by rmi22186** [comment]
Hi @dotomaz ! Thanks for the issue. It looks like something must have happened with our build process.  I just published it manually. It's now at 2.0.5.  It takes npm a bit for the update to reflect on the link above, but if you do a search for it it will show 2.0.5 now. Also if you try updating it should work.  Closing this as resolved.
