### ISSUE TITLE
Conflicts with existing Appboy instance

### ISSUE THREAD

**Issue by luads** [mparticle-integrations/mparticle-javascript-integration-appboy#38]
In our product, we already have Appboy configured and running for other Braze features. When we tried adding this kit, it broke our existing integration.

Would it be possible to have a check whether `window.appboy` is already defined prior to overwriting it?

**Comment by alexs-mparticle** [comment]
Thanks for reporting this. We're going to review this issue and respond back with a resolution as soon as possible.

**Comment by alexs-mparticle** [comment]
Tracked internally as 68447

**Comment by rmi22186** [comment]
I'm going to close this since we've helped resolve your specific use case internally.  We still have upgrading Braze to the latest version on our roadmap, and once that is released you'll be notified.  I'll also comment on this issue as well.
