### ISSUE TITLE
Integration with Nuxt TypeScript project - ReferenceError - window is not defined

### ISSUE THREAD

**Issue by 2beens** [mparticle-integrations/mparticle-javascript-integration-appboy#41]
When trying to register the Appboy/Braze kit into mParticle Web SDK, within the `Nuxt TypeScript` project, getting the following error:
```js
ReferenceError
window is not defined
```

I believe it might be related to the way console log is called within that function:
https://github.com/mparticle-integrations/mparticle-javascript-integration-appboy/blob/4e340cc5d4b47a8081860b4ad73ca5daf70da3b4/src/AppboyKit-dev.js#L555

If we check how `register` function is defined in the Google Analytics Kit for example, which registers just fine, just `console.log(...)` is used, instead of `window.console.log(...)`:
https://github.com/mparticle-integrations/mparticle-javascript-integration-google-analytics/blob/9329d8c7c35628e12efd9e7ee0614aebecdbc897/src/GoogleAnalyticsEventForwarder.js#L720

**Comment by 2beens** [comment]
I have imported the lib in a different way, which works, closing.

**Comment by mikhailsednev** [comment]
@2beens Hi! Could you describe how you solved the issue? Do you use selfhosting?
